{{- if .Values.operator.subscriptionEnabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ include "f5-ai-security.operatorGroupName" . }}
  namespace: {{ .Values.productNamespaces.operator }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "f5-ai-security.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.operator.operatorGroupAllNamespaces }}
spec: {}
{{- else }}
spec:
  targetNamespaces:
    - {{ .Values.productNamespaces.operator }}
{{- end }}
{{- end }}
